# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20190303_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='user', help_text='\u6765\u6e90', max_length=200)),
                ('store_type', models.SmallIntegerField(choices=[(1, 'small'), (2, 'medium'), (3, 'large')], default=1)),
                ('name', models.CharField(help_text='\u5e97\u540d', max_length=100)),
                ('address', models.CharField(help_text='\u5730\u5740', max_length=200)),
                ('longitude', models.CharField(help_text='\u7ecf\u5ea6', max_length=100)),
                ('latitude', models.CharField(help_text='\u7eac\u5ea6', max_length=100)),
                ('linkman', models.CharField(help_text='\u8054\u7cfb\u4eba', max_length=20)),
                ('telephone', models.CharField(help_text='\u8054\u7cfb\u7535\u8bdd', max_length=20)),
                ('service_time', models.CharField(help_text='\u670d\u52a1\u65f6\u95f4', max_length=100)),
                ('images', models.CharField(help_text='\u56fe\u7247', max_length=1024)),
                ('status', models.SmallIntegerField(choices=[(0, '\u7981\u7528'), (1, '\u6b63\u5e38')], default=1)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='submittedpoint',
            unique_together=set([('source', 'longitude', 'latitude')]),
        ),
    ]
