# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20190324_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedpoint',
            name='images',
            field=models.CharField(blank=True, default='', help_text='\u56fe\u7247', max_length=1024),
        ),
        migrations.AlterField(
            model_name='submittedpoint',
            name='linkman',
            field=models.CharField(blank=True, default='', help_text='\u8054\u7cfb\u4eba', max_length=20),
        ),
        migrations.AlterField(
            model_name='submittedpoint',
            name='service_time',
            field=models.CharField(blank=True, default='', help_text='\u670d\u52a1\u65f6\u95f4', max_length=100),
        ),
        migrations.AlterField(
            model_name='submittedpoint',
            name='telephone',
            field=models.CharField(blank=True, default='', help_text='\u8054\u7cfb\u7535\u8bdd', max_length=20),
        ),
    ]
