# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-23 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_type', models.SmallIntegerField(choices=[(1, 'small'), (2, 'medium'), (3, 'large')], default=1)),
                ('identity', models.CharField(default=shortuuid.main.uuid, help_text='\u552f\u4e00\u6807\u8bc6', max_length=100)),
                ('province', models.CharField(help_text='\u7701', max_length=50)),
                ('city', models.CharField(help_text='\u5e02', max_length=50)),
                ('district', models.CharField(help_text='\u533a', max_length=50)),
                ('name', models.CharField(help_text='\u540d\u79f0', max_length=100)),
                ('address', models.CharField(help_text='\u5730\u5740', max_length=200)),
                ('longitude', models.CharField(help_text='\u7ecf\u5ea6', max_length=100)),
                ('latitude', models.CharField(help_text='\u7eac\u5ea6', max_length=100)),
                ('linkman', models.CharField(help_text='\u8054\u7cfb\u4eba', max_length=20)),
                ('telephone', models.CharField(help_text='\u8054\u7cfb\u7535\u8bdd', max_length=20)),
                ('service_time', models.CharField(help_text='\u670d\u52a1\u65f6\u95f4', max_length=100)),
                ('status', models.SmallIntegerField(choices=[(0, '\u7981\u7528'), (1, '\u6b63\u5e38')], default=1)),
                ('raw_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.RawPoint')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='point',
            unique_together=set([('raw_point',), ('identity',)]),
        ),
    ]
