# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-03 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='\u5e02', max_length=50)),
                ('name', models.CharField(help_text='\u540d\u79f0', max_length=100)),
                ('longitude', models.CharField(help_text='\u7ecf\u5ea6', max_length=100)),
                ('latitude', models.CharField(help_text='\u7eac\u5ea6', max_length=100)),
                ('status', models.SmallIntegerField(choices=[(0, '\u7981\u7528'), (1, '\u6b63\u5e38')], default=1)),
            ],
        ),
    ]
