# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-03 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_poi'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='image',
            field=models.CharField(default='', help_text='\u5730\u5740\u56fe\u7247', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='order',
            field=models.IntegerField(default=100, help_text='\u6392\u5e8f'),
        ),
    ]
