# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190303_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(help_text='\u5e97\u540d', max_length=100),
        ),
        migrations.RemoveField(
            model_name='point',
            name='raw_point',
        ),
        migrations.AlterUniqueTogether(
            name='point',
            unique_together=set([('identity',)]),
        ),
    ]
